
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
